version: '3.8'

services:
  # client:
  #   build: ./Client
  #   networks:
  #     app-network:
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./Client:/app
  #   command: npm run dev
  # env_file:
  #   - ./Client/.env

  server:
    container_name: api-node
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    command: npm run dev
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env

#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge
